name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: sudo apt install pkg-config libx11-dev libxi-dev libgl1-mesa-dev libasound2-dev && rustup target add wasm32-unknown-unknown && cargo build --target wasm32-unknown-unknown 
    - uses: actions/upload-artifact@v4
      with: 
        name: football.wasm
        path: /home/runner/work/football/football/target/wasm32-unknown-unknown/debug/football_translate.wasm
